/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemkampus_beta;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fuad Hanif S
 */
public class Nilai_mhs extends javax.swing.JFrame {
koneksi kon=new koneksi();
private Object [][] datanilai=null;
private String[]label={"No.Laporan","NIM","Nama","Mata Kuliaht","Tugas","UTS","UAS","Hitung","Keterangant"};

    /**
     * Creates new form Nilai_mhs
     */
    public Nilai_mhs() {
        initComponents();
        kon.config();
        BacaTabelNilai();
    }
    
   private void BacaTabelNilai(){
    try
    {
        String sql="Select *From nilai order by no_laporan";
        kon.rs=kon.st.executeQuery(sql);
        ResultSetMetaData m=kon.rs.getMetaData();
        int kolom=m.getColumnCount();
        int baris=0;
        while(kon.rs.next())
            {
                baris=kon.rs.getRow();
            }
    datanilai=new Object[baris][kolom];
    int x=0;
    kon.rs.beforeFirst();
    while(kon.rs.next())
        {
            datanilai[x][0]=kon.rs.getString("No_Laporan");
            datanilai[x][1]=kon.rs.getString("NIM");
            datanilai[x][2]=kon.rs.getString("Nama");
            datanilai[x][3]=kon.rs.getString("Mata_Kuliah");
            datanilai[x][4]=kon.rs.getString("Tugas");
            datanilai[x][5]=kon.rs.getString("UTS");
            datanilai[x][6]=kon.rs.getString("UAS");
            datanilai[x][7]=kon.rs.getString("Hitung");
            datanilai[x][8]=kon.rs.getString("Keterangan");
            x++;
        }
    tableNilai.setModel(new DefaultTableModel(datanilai,label));
    }
    catch(SQLException e)
    {
        JOptionPane.showMessageDialog(null, e);
    }
    }
    
    private void BacaTabelNilai2(){
    try
    {
        String sql="select *from nilai where no_laporan like '%" +tCari.getText()+ "%' "
                    +" or nim like '%"+tCari.getText()+"%'"
                    +" or nama like '%"+tCari.getText()+"%'"
                    +" or mata_kuliah like '%"+tCari.getText()+"%'";
        kon.rs=kon.st.executeQuery(sql);
        ResultSetMetaData m=kon.rs.getMetaData();
        int kolom=m.getColumnCount();
        int baris=0;
        while(kon.rs.next())
            {
                baris=kon.rs.getRow();
            }
    datanilai=new Object[baris][kolom];
    int x=0;
    kon.rs.beforeFirst();
    while(kon.rs.next())
        {
            datanilai[x][0]=kon.rs.getString("No_Laporan");
            datanilai[x][1]=kon.rs.getString("NIM");
            datanilai[x][2]=kon.rs.getString("Nama");
            datanilai[x][3]=kon.rs.getString("Mata_Kuliah");
            datanilai[x][4]=kon.rs.getString("Tugas");
            datanilai[x][5]=kon.rs.getString("UTS");
            datanilai[x][6]=kon.rs.getString("UAS");
            datanilai[x][7]=kon.rs.getString("Hitung");
            datanilai[x][8]=kon.rs.getString("Keterangan");
            x++;
        }
    tableNilai.setModel(new DefaultTableModel(datanilai,label));
    }
    catch(SQLException e)
    {
        JOptionPane.showMessageDialog(null, e);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableNilai = new javax.swing.JTable();
        TabelDataNilai = new javax.swing.JLabel();
        Pencarian = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 159, 178));

        tableNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No. Laporan", "NIM", "Nama", "Mata Kuliah", "Tugas", "UTS", "UAS", "Hitung", "Keterangan"
            }
        ));
        jScrollPane2.setViewportView(tableNilai);

        TabelDataNilai.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        TabelDataNilai.setForeground(new java.awt.Color(255, 255, 255));
        TabelDataNilai.setText("Tabel Data Nilai");

        Pencarian.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Pencarian.setForeground(new java.awt.Color(255, 255, 255));
        Pencarian.setText("Pencarian");

        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tCariKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCariKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Pencarian)
                        .addGap(18, 18, 18)
                        .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TabelDataNilai)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(TabelDataNilai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pencarian)
                    .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemkampus_beta/Images/Lollipop-Android-Wallpaper-by-Puscifer911.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 390));

        setSize(new java.awt.Dimension(1023, 426));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCariKeyPressed

    private void tCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyTyped
      kon.config();
       BacaTabelNilai2();
    }//GEN-LAST:event_tCariKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nilai_mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nilai_mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nilai_mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nilai_mhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nilai_mhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pencarian;
    private javax.swing.JLabel TabelDataNilai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tCari;
    private javax.swing.JTable tableNilai;
    // End of variables declaration//GEN-END:variables
}
